package context

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90-dev

import (
	"context"

	"github.com/99designs/gqlgen/plugin/federation/testdata/context/generated"
	model "github.com/99designs/gqlgen/plugin/federation/testdata/context/generated/models"
)

// FindTransactionByID is the resolver for the findTransactionByID field.
func (r *entityResolver) FindTransactionByID(ctx context.Context, id string) (*model.Transaction, error) {
	return &model.Transaction{
		ID:     id,
		Amount: 100,
	}, nil
}

// FindUserByID is the resolver for the findUserByID field.
func (r *entityResolver) FindUserByID(ctx context.Context, id string) (*model.User, error) {
	return &model.User{
		ID:           id,
		UserCurrency: "USD",
	}, nil
}

// Entity returns generated.EntityResolver implementation.
func (r *Resolver) Entity() generated.EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
