package context

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90-dev

import (
	"context"
	"fmt"

	"github.com/99designs/gqlgen/plugin/federation/testdata/context/generated"
	model "github.com/99designs/gqlgen/plugin/federation/testdata/context/generated/models"
)

// Transaction is the resolver for the transaction field.
func (r *queryResolver) Transaction(ctx context.Context) (*model.Transaction, error) {
	return &model.Transaction{ID: "txn-1", Amount: 100}, nil
}

// AmountInUserCurrency is the resolver for the amountInUserCurrency field.
//
// currencyCode is the @fromContext contextual argument. At runtime the router
// resolves it from the User ancestor's @context and delivers it here as an
// ordinary field argument.
func (r *transactionResolver) AmountInUserCurrency(ctx context.Context, obj *model.Transaction, currencyCode *string) (string, error) {
	currency := "USD"
	if currencyCode != nil {
		currency = *currencyCode
	}
	return fmt.Sprintf("%d %s", obj.Amount, currency), nil
}

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Transaction returns generated.TransactionResolver implementation.
func (r *Resolver) Transaction() generated.TransactionResolver { return &transactionResolver{r} }

type queryResolver struct{ *Resolver }
type transactionResolver struct{ *Resolver }
